name: bzroot
on:
  # push:
  #   paths: 'CICD/Dockerfile'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bobbintb
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get UnRAID version
        run: |
          sudo apt update
          sudo apt install dracut
          chmod +x bzroot.sh
          sudo ./bzroot.sh
          pwd
          ls -ls
          cd ./bzroot
          docker build -t bobbintb/unraid-bzroot .
          docker push bobbintb/unraid-bzroot
          VERSION_ID=$(docker run --rm bobbintb/unraid-bzroot /bin/bash -c ". /etc/os-release && echo \$VERSION_ID")
          docker build -t bobbintb/unraid-bzroot:$VERSION_ID .
          docker push bobbintb/unraid-bzroot:$VERSION_ID
