name: 2 - CICD-base
on:
  # push:
  #   paths: 'CICD/Dockerfile'
  # workflow_run:
  #   workflows: ["bzroot"]
  #   types:
  #     - completed
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bobbintb
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get UnRAID version
        run: |
          chmod +x CICD-base.sh
          sudo ./CICD-base.sh
          pwd
          ls -ls
          cd ./CICD-base
          docker build -t bobbintb/unraid-cicd-base .
          docker push bobbintb/unraid-cicd-base
          VERSION_ID=$(docker run --rm bobbintb/unraid-cicd-base /bin/bash -c ". /etc/os-release && echo \$VERSION_ID")
          docker build -t bobbintb/unraid-cicd-base:$VERSION_ID .
          docker push bobbintb/unraid-cicd-base:$VERSION_ID
