name: CICD-builder
on:
  #push:
  #  paths: 'CICD/Dockerfile'
  workflow_run:
    workflows: ["CICD"]
    types:
      - completed
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bobbintb
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get UnRAID version
        run: |
          cd ./CICD-builder
          docker build -t bobbintb/unraid-cicd-builder .
          docker push bobbintb/unraid-cicd-builder
          VERSION_ID=$(docker run --rm bobbintb/unraid-cicd-builder /bin/bash -c ". /etc/os-release && echo \$VERSION_ID")
          docker build -t bobbintb/unraid-cicd-builder:$VERSION_ID .
          docker push bobbintb/unraid-cicd-builder:$VERSION_ID
